services:
  reminder-server:
    build: 
      context: .
      args:
          ARCH: 
    image: reminder-server:latest
    volumes:
        - ./reminders.json:/app/reminders.json
        - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
        TZ: Asia/Tokyo
        NODE_ENV: production
        PORT: 
        STORAGE_FILE: 
        ALLOW_DOMAIN: 
        SSL_KEY: 
        SSL_CERT: 
    ports:
        - 3000:3000
    init: true
    restart: always
