import { GetCommand, ScanCommand, DeleteCommand } from '@aws-sdk/lib-dynamodb';
import { ListObjectVersionsCommand, DeleteObjectsCommand } from '@aws-sdk/client-s3';
import type { StoredReminder } from '../../../../src/reminders/types.ts';
import type { SuiteFixture, CleanupSummary } from './types.ts';
import { fixtureState } from './fixture.ts';
export async function readOwnerState(fixture: SuiteFixture, ownerId: string): Promise<{ itemCount: number; imageBytes: number }> { if (!/^[a-f0-9]{64}$/.test(ownerId)) throw new Error('OWNER_REJECTED'); const result = await fixture.clients.dynamodb.send(new GetCommand({ TableName: fixture.config.ownerStateTable, Key: { pk: `OWNER#${ownerId}`, sk: 'STORAGE' }, ConsistentRead: true })); const itemCount = result.Item?.itemCount ?? 0; const imageBytes = result.Item?.imageBytes ?? 0; if (![itemCount, imageBytes].every(value => Number.isSafeInteger(value) && value >= 0)) throw new Error('STORAGE_MISMATCH'); return { itemCount, imageBytes }; }
export async function readReminder(fixture: SuiteFixture, ownerId: string, id: string): Promise<StoredReminder | null> { if (!/^[a-f0-9]{64}$/.test(ownerId)) throw new Error('OWNER_REJECTED'); const result = await fixture.clients.dynamodb.send(new GetCommand({ TableName: fixture.config.remindersTable, Key: { ownerId, id }, ConsistentRead: true })); return (result.Item as StoredReminder | undefined) ?? null; }
/** The tables/bucket are wholly run-owned; reset only after suite log resolution. */
export async function resetStorage(fixture: SuiteFixture): Promise<CleanupSummary> {
  const state = fixtureState(fixture); if (state.outstanding || state.cleanupIntervals.some(i => !i.completed)) throw new Error('QUIESCENCE_REJECTED');
  const result: CleanupSummary = { attempted: 0, succeeded: 0, errors: 0, leaks: 0 };
  for (const [TableName, names] of [[fixture.config.remindersTable, ['ownerId', 'id']], [fixture.config.ownerStateTable, ['pk', 'sk']], [fixture.config.imageJobsTable, ['jobId']]] as const) { let ExclusiveStartKey: Record<string, unknown> | undefined; do { const page = await fixture.clients.dynamodb.send(new ScanCommand({ TableName, ConsistentRead: true, ...(ExclusiveStartKey ? { ExclusiveStartKey } : {}) })); for (const item of page.Items ?? []) { result.attempted++; await fixture.clients.dynamodb.send(new DeleteCommand({ TableName, Key: Object.fromEntries(names.map(name => [name, item[name]])) })); result.succeeded++; } ExclusiveStartKey = page.LastEvaluatedKey; } while (ExclusiveStartKey); const check = await fixture.clients.dynamodb.send(new ScanCommand({ TableName, ConsistentRead: true, Select: 'COUNT' })); if (check.Count !== 0 || check.LastEvaluatedKey) throw new Error('STORAGE_RESET_FAILED'); }
  let KeyMarker: string | undefined; let VersionIdMarker: string | undefined; const Bucket = fixture.config.imagesBucket;
  do { const page = await fixture.clients.s3.send(new ListObjectVersionsCommand({ Bucket, ...(KeyMarker ? { KeyMarker } : {}), ...(VersionIdMarker ? { VersionIdMarker } : {}) })); const Objects = [...(page.Versions ?? []), ...(page.DeleteMarkers ?? [])].map(item => ({ Key: item.Key!, VersionId: item.VersionId! })); if (Objects.length) { result.attempted += Objects.length; const removed = await fixture.clients.s3.send(new DeleteObjectsCommand({ Bucket, Delete: { Objects } })); if (removed.Errors?.length) throw new Error('STORAGE_RESET_FAILED'); result.succeeded += Objects.length; } KeyMarker = page.NextKeyMarker; VersionIdMarker = page.NextVersionIdMarker; if (page.IsTruncated && !KeyMarker) throw new Error('STORAGE_RESET_FAILED'); } while (KeyMarker);
  const page = await fixture.clients.s3.send(new ListObjectVersionsCommand({ Bucket })); if (page.IsTruncated || page.Versions?.length || page.DeleteMarkers?.length) throw new Error('STORAGE_RESET_FAILED'); return result;
}

/** Refusal-local comparison; hashes and rows are never public evidence. */
export async function snapshotOwnedStorage(fixture: SuiteFixture, options: { excludeRate?: boolean } = {}): Promise<string> {
  const { createHash } = await import('node:crypto'); const rows: string[] = [];
  for (const TableName of [fixture.config.remindersTable, fixture.config.ownerStateTable, fixture.config.imageJobsTable]) { let ExclusiveStartKey: Record<string, unknown> | undefined; do { const page = await fixture.clients.dynamodb.send(new ScanCommand({ TableName, ConsistentRead: true, ...(ExclusiveStartKey ? { ExclusiveStartKey } : {}) })); rows.push(...(page.Items ?? []).filter(item => !(options.excludeRate && TableName === fixture.config.ownerStateTable && String(item.sk).startsWith('RATE#'))).map(item => JSON.stringify([TableName, Object.fromEntries(Object.entries(item).sort(([a], [b]) => a.localeCompare(b)))]))); ExclusiveStartKey = page.LastEvaluatedKey; } while (ExclusiveStartKey); }
  let KeyMarker: string | undefined; let VersionIdMarker: string | undefined; do { const page = await fixture.clients.s3.send(new ListObjectVersionsCommand({ Bucket: fixture.config.imagesBucket, ...(KeyMarker ? { KeyMarker } : {}), ...(VersionIdMarker ? { VersionIdMarker } : {}) })); rows.push(...[...(page.Versions ?? []), ...(page.DeleteMarkers ?? [])].map(item => JSON.stringify([item.Key, item.VersionId, 'Size' in item ? item.Size : 0]))); KeyMarker = page.NextKeyMarker; VersionIdMarker = page.NextVersionIdMarker; if (page.IsTruncated && !KeyMarker) throw new Error('STORAGE_MISMATCH'); } while (KeyMarker);
  return createHash('sha256').update(rows.sort().join('\0')).digest('hex');
}
